name: Test JMeter Action

on:
  workflow_dispatch:
    inputs:
      total_threads:
        description: "Total number of threads (users) for the test"
        required: true
        default: 1000
      runners:
        description: "Number of runners for distributed testing"
        required: true
        default: 5


jobs:
  jmeter-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runner: [1, 2, 3, 4, 5]

    steps:
      - uses: actions/checkout@v2

      - name: Lint all YAML files in the directory
        uses: ibiqlik/action-yamllint@master

      - name: Run JMeter Action
        uses: ./
        with:
          testFilePath: test/test2.jmx
          outputReportsFolder: reports/
          args: "--loglevel INFO"
          plugins: "jpgc-casutg"

      - name: Run More Than One JMeter Action
        uses: ./
        with:
          testFilePath: test/
          outputReportsFolder: reports/
          args: "--loglevel INFO"

      - uses: actions/upload-artifact@v4
        with:
          name: jmeter-test-results
          path: reports/
