name: Test JMeter Action

on:
  workflow_dispatch:
    inputs:
      total_threads:
        description: "Total number of threads (users) for the test"
        required: true
        default: 1000
      runners:
        description: "Number of runners for distributed testing"
        required: true
        default: 5

  schedule:
    - cron: '1/14 * * * *'


jobs:
  jmeter-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runner: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]

    steps:
      - name: Increase system limits
        run: |
          sudo sysctl -w net.ipv4.ip_local_port_range="1024 65535"
          sudo sysctl -w net.ipv4.tcp_fin_timeout=30
          sudo sysctl -w net.core.somaxconn=65535
      - uses: actions/checkout@v2

      - name: Lint all YAML files in the directory
        uses: ibiqlik/action-yamllint@master

      - name: Run JMeter Action
        env:
          JVM_ARGS: "-Xmx2048m"
        uses: rbhadti94/apache-jmeter-action@v0.7.0
        with:
          testFilePath: test/test2.jmx
          outputReportsFolder: reports-${{ matrix.runner }}/
          args: "--loglevel INFO"
          plugins: "jpgc-casutg"

      - uses: actions/upload-artifact@v4
        with:
          name: jmeter-results-${{ matrix.runner }}
          path: reports-${{ matrix.runner }}/
